"""Generate a whole-block at-a-glance overview from the per-week plan files.

The `weeks/week_YYYY-MM-DD.md` files remain the single source of truth. This
script derives `plans/2026-half-marathon/BLOCK_OVERVIEW.md` from them so the
block arc (mileage ramp, down weeks, workout rhythm) is visible on one screen
without opening every week file. The output is generated -- do not edit it by
hand; edit the week files and re-run this script.
"""

from __future__ import annotations

import re
from datetime import date

from weekly_plan import WEEKS_DIR, WeekPlan, parse_week_file

OVERVIEW_PATH = WEEKS_DIR.parent / "BLOCK_OVERVIEW.md"
GENERATED_BANNER = "<!-- generated by scripts/block_overview.py; do not edit by hand -->"
DAY_ORDER = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def iter_week_starts() -> list[date]:
    """Return every block week start, in chronological order."""
    starts: list[date] = []
    for path in sorted(WEEKS_DIR.glob("week_*.md")):
        match = re.search(r"(\d{4}-\d{2}-\d{2})", path.name)
        if match:
            starts.append(date.fromisoformat(match.group(1)))
    return sorted(set(starts))


def short_tag(purpose: str) -> str:
    """Compress a day's purpose into a short scannable workout tag."""
    p = purpose.lower()
    if "long run" in p:
        return "LR"
    if "hmp" in p or "half-marathon pace" in p or "half marathon pace" in p:
        return "HMP"
    if "strength" in p:
        return "str"
    if "threshold" in p:
        return "thr"
    if "speed" in p:
        return "spd"
    if "tempo" in p:
        return "tempo"
    if "stamina" in p:
        return "stam"
    if "sharpen" in p or "stride" in p:
        return "strd"
    if "sos" in p:
        return "SOS"
    return "ez"


def short_run(planned: str, purpose: str) -> str:
    """Render a single grid cell: leading mileage plus a short workout tag."""
    run = planned.strip()
    if run.lower().startswith("off") or not run:
        return "Off"
    if purpose.strip().lower() == "race":
        return "**RACE**"
    miles_match = re.match(r"(\d+(?:\.\d+)?(?:\s*-\s*\d+(?:\.\d+)?)?)", run)
    miles = miles_match.group(1).replace(" ", "") if miles_match else run
    tag = short_tag(purpose)
    cell = f"{miles} {tag}".strip()
    if "sos" in purpose.lower():
        cell = f"**{cell}**"
    return cell


def target_midpoint(target: str) -> float | None:
    """Extract a numeric midpoint from a target-mileage string for deltas."""
    match = re.search(r"(\d+)(?:\s*-\s*(\d+))?", target)
    if not match:
        return None
    low = int(match.group(1))
    high = int(match.group(2)) if match.group(2) else low
    return (low + high) / 2


def clean_target(target: str) -> str:
    """Trim boilerplate so the target column stays compact."""
    return re.sub(r"\babout\b\s*", "", target).split(" before ")[0].strip()


def long_run_cell(week: WeekPlan) -> str:
    for day in week.day_plans:
        if "long run" in day.purpose.lower():
            return short_run(day.planned, day.purpose).replace("**", "")
    for day in week.day_plans:
        if day.purpose.strip().lower() == "race":
            return "race"
    return "-"


def sos_days_cell(week: WeekPlan) -> str:
    days = [
        day.day_name[:3]
        for day in week.day_plans
        if "sos" in day.purpose.lower()
    ]
    return ", ".join(days) if days else "-"


def render(weeks: list[WeekPlan]) -> str:
    lines: list[str] = [
        GENERATED_BANNER,
        "",
        "# 2026 Half-Marathon Block - At a Glance",
        "",
        "Generated from `weeks/week_YYYY-MM-DD.md` (the source of truth). "
        "Edit a week file and re-run `scripts/block_overview.py` to refresh.",
        "",
        "Cells show leading mileage plus a short tag "
        "(`LR` long run, `HMP` half-marathon pace, `str` strength, "
        "`thr` threshold, `strd` strides, `ez` easy). **Bold** marks SOS days.",
        "",
        "## Week Grid",
        "",
        "| Wk | Week of | " + " | ".join(DAY_ORDER) + " | Target |",
        "| --- | --- | " + " | ".join(["---"] * len(DAY_ORDER)) + " | --- |",
    ]
    for number, week in enumerate(weeks, start=1):
        cells = [short_run(day.planned, day.purpose) for day in week.day_plans]
        cells += [""] * (len(DAY_ORDER) - len(cells))
        lines.append(
            f"| {number} | {week.week_start.isoformat()} | "
            + " | ".join(cells[: len(DAY_ORDER)])
            + f" | {clean_target(week.target_mileage)} |"
        )

    lines += [
        "",
        "## Block Arc",
        "",
        "| Wk | Week of | Target | Delta | Long run | SOS days | Primary purpose |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    prev_mid: float | None = None
    for number, week in enumerate(weeks, start=1):
        mid = target_midpoint(week.target_mileage)
        if mid is None or prev_mid is None:
            delta = "-"
        else:
            diff = mid - prev_mid
            delta = f"+{diff:g}" if diff > 0 else (f"{diff:g}" if diff < 0 else "0")
        prev_mid = mid if mid is not None else prev_mid
        lines.append(
            f"| {number} | {week.week_start.isoformat()} "
            f"| {clean_target(week.target_mileage)} | {delta} "
            f"| {long_run_cell(week)} | {sos_days_cell(week)} "
            f"| {week.primary_purpose} |"
        )
    return "\n".join(lines) + "\n"


def build() -> str:
    weeks: list[WeekPlan] = []
    for week_start in iter_week_starts():
        plan = parse_week_file(week_start)
        if plan is not None:
            weeks.append(plan)
    if not weeks:
        raise SystemExit(f"No week files found under {WEEKS_DIR}")
    return render(weeks)


def main() -> None:
    OVERVIEW_PATH.write_text(build())
    print(f"Wrote {OVERVIEW_PATH.relative_to(WEEKS_DIR.parent.parent.parent)}")


if __name__ == "__main__":
    main()
