#!/usr/bin/env python3
"""Generate STATUS.md — the one-file 'am I on track?' digest.

Reads weekly-log auto-summary blocks only (never raw daily entries): the
record/view contract says views are built from what weekly_entries.py already
distilled. Fails loud on unparseable blocks rather than guessing numbers.
"""
from __future__ import annotations

import argparse
import re
from datetime import date, timedelta
from pathlib import Path

BLOCK_START = date(2026, 8, 3)
RACE_DAY = date(2026, 12, 6)
BLOCK_WEEKS = 18
MARKER = re.compile(r"<!-- auto-summary:start -->\n(?P<body>.*?)<!-- auto-summary:end -->", re.DOTALL)
FIELD = re.compile(r"^- (?P<key>[^:]+): ?(?P<value>.*)$")


def parse_summary(path: Path) -> dict[str, str]:
    match = MARKER.search(path.read_text())
    if match is None:
        raise SystemExit(f"{path.name}: no auto-summary block")
    fields: dict[str, str] = {}
    for line in match.group("body").splitlines():
        field = FIELD.match(line.strip())
        if field:
            fields[field.group("key")] = field.group("value")
    required = {"Target mileage", "Actual mileage so far", "Status"}
    missing = required - fields.keys()
    if missing:
        raise SystemExit(f"{path.name}: auto-summary missing {sorted(missing)}")
    return fields


def week_start_of(path: Path) -> date:
    return date.fromisoformat(path.stem.removeprefix("week_"))


def build(repo_root: Path, today: date) -> str:
    weekly_dir = repo_root / "logs" / "weekly"
    files = sorted(weekly_dir.glob("week_*.md"))
    if not files:
        raise SystemExit(f"no weekly logs under {weekly_dir}")
    summaries = {week_start_of(p): parse_summary(p) for p in files}
    current_start = today - timedelta(days=today.weekday())
    current = summaries.get(current_start)

    lines = [
        "<!-- generated by scripts/status_digest.py; do not edit by hand -->",
        "",
        "# Training Status",
        "",
        f"Updated {today.isoformat()}. Regenerate: `.venv/bin/python scripts/status_digest.py`.",
        "",
        f"## Current Week (week of {current_start.isoformat()})",
        "",
    ]
    if current is None:
        lines.append("- No weekly log yet for this week.")
    else:
        for key in ("Target mileage", "Actual mileage so far", "Status",
                    "Primary purpose", "Days", "Warnings"):
            if key in current:
                lines.append(f"- {key}: {current[key]}")
    block_week = (current_start - BLOCK_START).days // 7 + 1
    position = (
        f"week {block_week} of {BLOCK_WEEKS}" if 1 <= block_week <= BLOCK_WEEKS
        else "pre-block ramp" if block_week < 1 else "post-block"
    )
    lines += [
        "",
        "## Block Position",
        "",
        f"- 2026 half-marathon block: {position} (starts {BLOCK_START.isoformat()}, race {RACE_DAY.isoformat()})",
        "- Grid: `plans/2026-half-marathon/BLOCK_OVERVIEW.md`; facts/rules: `sources/00_canonical_context.md`",
        "",
        "## Recent Weeks",
        "",
        "| Week of | Target | Actual | Status |",
        "| --- | --- | --- | --- |",
    ]
    for start in sorted(summaries)[-4:]:
        fields = summaries[start]
        lines.append(
            f"| {start.isoformat()} | {fields['Target mileage']} | "
            f"{fields['Actual mileage so far']} | {fields['Status']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path,
                        default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--today", type=date.fromisoformat, default=date.today())
    args = parser.parse_args()
    output = build(args.repo_root, args.today)
    (args.repo_root / "STATUS.md").write_text(output)
    print(f"wrote {args.repo_root / 'STATUS.md'}")


if __name__ == "__main__":
    main()
